plugins {
    id 'java-library'
}
java {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
}
dependencies {
    implementation project(path: ':annotation-module', configuration: 'default')
    implementation project(path: ':common-library', configuration: 'default')
    implementation libs.auto.service
    annotationProcessor libs.auto.service
    implementation libs.javapoet
}